### ISSUE TITLE
Pantallas de inicio de sesión

### ISSUE THREAD

**Issue by samueltorresfau** [UNIZAR-30226-2021-11/Guinyote_app#3]
Creación de las actividades necesarias para el inicio de sesión o bien el registro en el sistema.

Correspondiente a las pantallas 'Pantalla de inicio de sesión' y 'Pantalla de registro' del mapa de navegación

**Comment by daniPerez99** [comment]
- Recordatorio de credenciales(Guardarlas en la base con hash)
- confirmación por correo electrónico
- borrado de cuenta
